function exe_return_humanoid_sceleton_anim_cycle_09()
{
	var _struct =
		{
			noone_cycle :			[],
			
			
			walk_R_01_flat :		[	["walk_passing_R",15,[0,1,1],["col_ass_fwd","col_shd_right","col_shd_left"]],	["walk_up_R",15,[0,1,1],["col_ass_fwd","col_shd_right","col_shd_left"]],	["walk_contact_R",10,[0,1,1],["anchor_fwd_ground_C","rec_Ltoe","fwd_step_up","fwd_step_flat","fwd_step_down","col_ass_fwd","col_shd_right","col_shd_left"]],	["walk_down_R",10,[0,1,1],["anchor_fwd_ground_C","rec_Ltoe","fwd_step_up","fwd_step_flat","fwd_step_down","col_ass_fwd","col_shd_right","col_shd_left"]],	["walk_ddown_R",10,[0,1,1],["anchor_fwd_ground_C","rec_Ltoe","fwd_step_up","fwd_step_flat","fwd_step_down","col_ass_fwd","col_shd_right","col_shd_left"]],	["walk_d3own_R",15,[0,1,1],["anchor_fwd_ground_C","rec_Ltoe","fwd_step_up","fwd_step_flat","fwd_step_down","col_ass_fwd","col_shd_right","col_shd_left"]],			["walk_d4own_R",15,[0,1,1],["anchor_fwd_ground_C","rec_Ltoe","fwd_step_up","fwd_step_flat","fwd_step_down","col_ass_fwd","col_shd_right","col_shd_left"]],		["walk_d5own_R",15,[0,1,1],["anchor_fwd_ground_C","rec_Ltoe","fwd_step_up","fwd_step_flat","fwd_step_down","col_ass_fwd","col_shd_right","col_shd_left"]],			],
			walk_L_01_flat :		[	["walk_passing_L",15,[0,1,1],["col_ass_fwd","col_shd_right","col_shd_left"]],	["walk_up_L",15,[0,1,1],["col_ass_fwd","col_shd_right","col_shd_left"]],	["walk_contact_L",10,[0,1,1],["anchor_fwd_ground_C","rec_Rtoe","fwd_step_up","fwd_step_flat","fwd_step_down","col_ass_fwd","col_shd_right","col_shd_left"]],	["walk_down_L",10,[0,1,1],["anchor_fwd_ground_C","rec_Rtoe","fwd_step_up","fwd_step_flat","fwd_step_down","col_ass_fwd","col_shd_right","col_shd_left"]],	["walk_ddown_L",10,[0,1,1],["anchor_fwd_ground_C","rec_Rtoe","fwd_step_up","fwd_step_flat","fwd_step_down","col_ass_fwd","col_shd_right","col_shd_left"]],	["walk_d3own_L",15,[0,1,1],["anchor_fwd_ground_C","rec_Rtoe","fwd_step_up","fwd_step_flat","fwd_step_down","col_ass_fwd","col_shd_right","col_shd_left"]],			["walk_d4own_L",15,[0,1,1],["anchor_fwd_ground_C","rec_Rtoe","fwd_step_up","fwd_step_flat","fwd_step_down","col_ass_fwd","col_shd_right","col_shd_left"]],		["walk_d5own_L",15,[0,1,1],["anchor_fwd_ground_C","rec_Rtoe","fwd_step_up","fwd_step_flat","fwd_step_down","col_ass_fwd","col_shd_right","col_shd_left"]],			],
			
			walk_R_01_stepup :		[	["walk_passing_R",15,[0,1,1],["col_ass_fwd","col_shd_right","col_shd_left"]],	["walk_up_R",15,[0,1,1],["col_ass_fwd","col_shd_right","col_shd_left"]],	["walk_step_up_R",15,[0,1,1],["col_ass_fwd","col_shd_right","col_shd_left"]],	["walk_step_up_down_R",10,[0,1,1],["anchor_fwd_ground_C","rec_Ltoe","fwd_step_up","fwd_step_flat","fwd_step_down","col_ass_fwd","col_shd_right","col_shd_left"]],	["walk_down_R",10,[0,1,1],["anchor_fwd_ground_C","rec_Ltoe","fwd_step_up","fwd_step_flat","fwd_step_down","col_ass_fwd","col_shd_right","col_shd_left"]],	["walk_ddown_R",10,[0,1,1],["anchor_fwd_ground_C","rec_Ltoe","fwd_step_up","fwd_step_flat","fwd_step_down","col_ass_fwd","col_shd_right","col_shd_left"]],	["walk_d3own_R",15,[0,1,1],["anchor_fwd_ground_C","rec_Ltoe","fwd_step_up","fwd_step_flat","fwd_step_down","col_ass_fwd","col_shd_right","col_shd_left"]],						["walk_d4own_R",15,[0,1,1],["anchor_fwd_ground_C","rec_Ltoe","fwd_step_up","fwd_step_flat","fwd_step_down","col_ass_fwd","col_shd_right","col_shd_left"]],		["walk_d5own_R",15,[0,1,1],["anchor_fwd_ground_C","rec_Ltoe","fwd_step_up","fwd_step_flat","fwd_step_down","col_ass_fwd","col_shd_right","col_shd_left"]],			],
			walk_L_01_stepup :		[	["walk_passing_L",15,[0,1,1],["col_ass_fwd","col_shd_right","col_shd_left"]],	["walk_up_L",15,[0,1,1],["col_ass_fwd","col_shd_right","col_shd_left"]],	["walk_step_up_L",15,[0,1,1],["col_ass_fwd","col_shd_right","col_shd_left"]],	["walk_step_up_down_L",10,[0,1,1],["anchor_fwd_ground_C","rec_Rtoe","fwd_step_up","fwd_step_flat","fwd_step_down","col_ass_fwd","col_shd_right","col_shd_left"]],	["walk_down_L",10,[0,1,1],["anchor_fwd_ground_C","rec_Rtoe","fwd_step_up","fwd_step_flat","fwd_step_down","col_ass_fwd","col_shd_right","col_shd_left"]],	["walk_ddown_L",10,[0,1,1],["anchor_fwd_ground_C","rec_Rtoe","fwd_step_up","fwd_step_flat","fwd_step_down","col_ass_fwd","col_shd_right","col_shd_left"]],	["walk_d3own_L",15,[0,1,1],["anchor_fwd_ground_C","rec_Rtoe","fwd_step_up","fwd_step_flat","fwd_step_down","col_ass_fwd","col_shd_right","col_shd_left"]],						["walk_d4own_L",15,[0,1,1],["anchor_fwd_ground_C","rec_Rtoe","fwd_step_up","fwd_step_flat","fwd_step_down","col_ass_fwd","col_shd_right","col_shd_left"]],		["walk_d5own_L",15,[0,1,1],["anchor_fwd_ground_C","rec_Rtoe","fwd_step_up","fwd_step_flat","fwd_step_down","col_ass_fwd","col_shd_right","col_shd_left"]],			],
			
			walk_R_01_stepdown :	[	["walk_passing_R",15,[0,1,1],["col_ass_fwd","col_shd_right","col_shd_left"]],	["walk_up_R",15,[0,1,1],["col_ass_fwd","col_shd_right","col_shd_left"]],	["walk_step_down_R",15,[0,1,1],["col_ass_fwd","col_shd_right","col_shd_left"]],	["walk_step_down2_R",15,[0,1,1],["anchor_fwd_ground_C","rec_Ltoe","fwd_step_up","fwd_step_flat","fwd_step_down","col_ass_fwd","col_shd_right","col_shd_left"]],	["walk_step_down3_R",10,[0,1,1],["anchor_fwd_ground_C","rec_Ltoe","fwd_step_up","fwd_step_flat","fwd_step_down","col_ass_fwd","col_shd_right","col_shd_left"]],				["walk_d4own_R",15,[0,1,1],["anchor_fwd_ground_C","rec_Ltoe","fwd_step_up","fwd_step_flat","fwd_step_down","col_ass_fwd","col_shd_right","col_shd_left"]],		["walk_d5own_R",15,[0,1,1],["anchor_fwd_ground_C","rec_Ltoe","fwd_step_up","fwd_step_flat","fwd_step_down","col_ass_fwd","col_shd_right","col_shd_left"]],			],
			walk_L_01_stepdown :	[	["walk_passing_L",15,[0,1,1],["col_ass_fwd","col_shd_right","col_shd_left"]],	["walk_up_L",15,[0,1,1],["col_ass_fwd","col_shd_right","col_shd_left"]],	["walk_step_down_L",15,[0,1,1],["col_ass_fwd","col_shd_right","col_shd_left"]],	["walk_step_down2_L",15,[0,1,1],["anchor_fwd_ground_C","rec_Rtoe","fwd_step_up","fwd_step_flat","fwd_step_down","col_ass_fwd","col_shd_right","col_shd_left"]],	["walk_step_down3_L",10,[0,1,1],["anchor_fwd_ground_C","rec_Rtoe","fwd_step_up","fwd_step_flat","fwd_step_down","col_ass_fwd","col_shd_right","col_shd_left"]],				["walk_d4own_L",15,[0,1,1],["anchor_fwd_ground_C","rec_Rtoe","fwd_step_up","fwd_step_flat","fwd_step_down","col_ass_fwd","col_shd_right","col_shd_left"]],		["walk_d5own_L",15,[0,1,1],["anchor_fwd_ground_C","rec_Rtoe","fwd_step_up","fwd_step_flat","fwd_step_down","col_ass_fwd","col_shd_right","col_shd_left"]],			],
			
		}
	return(_struct);
}